# Generated by Django 4.2.7 on 2025-10-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_queue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='barber',
        ),
    ]
