# Generated by Django 4.2.7 on 2025-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_queue', '0002_remove_queue_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='whom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
