# Generated by Django 5.2.5 on 2025-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Date of the service (text)', max_length=100)),
                ('service_name', models.CharField(help_text='Service name (text)', max_length=255)),
                ('barber_name', models.CharField(help_text='Barber name (text)', max_length=255)),
                ('amount', models.CharField(help_text='Service amount/price (text)', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CocktailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Date of the order (text)', max_length=100)),
                ('service_name', models.CharField(help_text='Cocktail/drink name (text)', max_length=255)),
                ('number_stol', models.IntegerField(help_text='Bartender name (text)')),
                ('amount', models.CharField(help_text='Price/amount (text)', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
