# Generated by Django 5.2.5 on 2025-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Date of the expense (text)', max_length=100)),
                ('description', models.TextField(help_text='What this expense was for')),
                ('amount', models.CharField(help_text='Expense amount (text)', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='cocktailorder',
            name='number_stol',
            field=models.IntegerField(help_text='Table number (integer)'),
        ),
    ]
