# Generated by Django 5.2.5 on 2025-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_expense_alter_cocktailorder_number_stol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accepted', 'Accepted')], default='pending', help_text='Order status', max_length=10),
        ),
    ]
