# Generated by Django 5.2.5 on 2025-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_cocktailorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('ready', 'Ready'), ('accepted', 'Accepted')], default='pending', help_text='Order status', max_length=10),
        ),
    ]
